[package]
name = "druidaw"
version = "0.1.0"
authors = ["Charles Saracco <crsaracco@gmail.com>"]
edition = "2018"

[dependencies]
druid = "0.5.0"
crossbeam-channel = "0.4.0"
hound = "3.4.0"
itertools = "0.8.2"
log = "0.4.8"
jack = "0.6.2"
arraydeque = "0.4.5"